Yelp/puppet-uchiwa

.travis.yml, manifests/config.pp, manifests/params.pp
Initial PR - Will see what comes out the back of the test result
=> Fix some issues with 3.7.* Puppet

manifests/config.pp, spec/acceptance/class_spec.rb, spec/classes/uchiwa_spec.rb
This file contains passwords and should be readable only to the
uchiwa service.
2 existing acceptance tests are failing for me -- the ones which compare JSON content -- but they also fail on the master branch, so they shouldn't be a blocker.
=> Ensure uchiwa.json is not world-readable

manifests/install.pp, spec/classes/uchiwa_spec.rb
By default the package is set to ensure latest - we were running with this,
which caused our preview environment to update. We fixed to the version running
in production - https://github.com/alphagov/pp-puppet/pull/735 but although the
package was downgraded, the service did not restart, hence adding the notify.
We had to downgrade because we hit a bug similar to
https://github.com/sensu/uchiwa/issues/272
=> Notify uchiwa service when package changes

manifests/init.pp, manifests/params.pp
This PR will properly type the port number.  This solves issues encountered when using the future parser.
=> Properly type port number

manifests/params.pp, spec/classes/uchiwa_spec.rb
New versions of puppetlabs/apt module show a warning if the repo_key_id hasn't the 40 digits.
=> Fix warning when installing sensu apt repository

README.markdown, manifests/params.pp
The `manage_repo` thing seemed to be a faq, enough to justify having it on the front page I think.
=> Try to cleanup doc and un-nest api definitions

README.markdown
The example in the README suggested using manage_repo in order to disable management of repo by uchiwa, but according to the actual code (and my experience), the variable should be install_repo.
=> Changed example code from manage_repo to install_repo

manifests/repo/apt.pp, metadata.json, spec/classes/uchiwa_spec.rb
Since the newest [sensu-puppet](https://github.com/sensu/sensu-puppet) module requires puppetlabs-apt >=2.0.0 it makes sense to me to migrate this to be puppetlabs-apt >=2.0.0 as well.
This is basically the same changes that @bleuchtang made in #45 except there are no merge conflicts as I pulled the latest master and made the changes there.
Closes #45
=> Update apt::source to use puppetlabs-apt 2.0.0+

manifests/init.pp, manifests/params.pp, spec/classes/uchiwa_spec.rb, templates/etc/sensu/uchiwa.json.erb
This PR adds support for the new `users` feature, introduced in uchiwa 0.10.0. This allows users to specify an array of credentials to access the uchiwa dashboard, rather than sharing the same set of keys.
This PR also fixes #46
=> Introducing users param in puppet-uchiwa

manifests/params.pp
The APT key fingerprint contained in this puppet module does not appear to match the sensu repo's.
This PR updates the $repo_key_id parameter in `puppet-uchiwa`, fixing the inconsistency.
=> Update apt key id

Gemfile
This commit reverts part of 1cb2805c, which I believe could be behind the cause of travis build failures. 
I'm raising this PR to trigger a travis build and test the changes.
=> Fix travis build

manifests/init.pp, manifests/params.pp, spec/classes/uchiwa_spec.rb, templates/etc/sensu/uchiwa.json.erb
The auth parameter has been introduced in uchiwa 0.13.0 in order to allow the user to specify a static RSA keypair for JWT signature validation.
This PR introduces support for this param in the puppet-uchiwa module.
=> Introduce auth parameter support in puppet-uchiwa

manifests/init.pp, manifests/install.pp, manifests/params.pp
This allows installing versions not yet
in the sensuapp repo manually.
For example:
wget::fetch { "http://dl.bintray.com/palourde/uchiwa/uchiwa_0.12.1-1_amd64.deb":
destination => "/root/uchiwa_0.12.1-1_amd64.deb",
timeout     => 0,
verbose     => false,
} ->
package { "uchiwa":
ensure => latest,
provider => dpkg,
source => "/root/uchiwa_0.12.1-1_amd64.deb"
} ->
class { 'uchiwa':
install_repo        => false,
install_package     => false,
manage_services     => true,
sensu_api_endpoints => [
{
ssl  => false,
host => '127.0.0.1',
port => 4567,
user => 'apiadmin',
pass => $api_pass,
}
]
This is useful as the sensu apt repository often falls way out of date, and this allows sysadmins to ensure they can get the latest version pretty easily without running my own apt repository.
=> Adding option to not install the uchiwa package

README.markdown, manifests/init.pp, manifests/params.pp, templates/etc/sensu/uchiwa.json.erb
Added SSL Support in ERB Template.
=> Issue #68 - Added SSL Support

manifests/repo/apt.pp, manifests/repo/yum.pp, spec/classes/uchiwa_spec.rb
This fix allow uchiwa and sensu to coexist on the same server
=> Renaming repo from sensu to uchiwa

templates/etc/sensu/uchiwa.json.erb
Hi,
Adding users in manifest:
```
users => [
{
'username' => 'user1,
'password' => 'pass1',
'readonly' => false,
},
{
'username' => 'user2',
'password' => 'pass2',
'readonly' => true,
}
],
```
in logs Uchiwa fails to start with not very intuitive error:
```
{"timestamp":"2016-06-01T12:23:10.461145438Z","level":"fatal","message":"Error decoding file /etc/sensu/uchiwa.json: invalid character '\"' after object key:value pair"}
```
configuration  `/etc/sensu/uchiwa.json` misses comma between `users` and  `ssl` sections.
"users": [
{
"username": "user1",
"password": "pass1",
"role": {
"readonly": false
}
},
{
"username": "user2",
"password": "pass2",
"role": {
"readonly": true
}
}
]    "no comma here"
"ssl": {
"certfile": "/etc/sensu/ssl/uchiwa.pem",
"keyfile": "/etc/sensu/ssl/uchiwa.key"
} …
=> users add - json missing  comma

templates/etc/sensu/uchiwa.json.erb
Hi,
Patch removes extra empty lines in the config, although Im not sure why it has "tab" between bracket and comma.
```
"timeout": 5
}    ,
{
"name": "sensu",
```
=> Remove empty lines

README.markdown, manifests/init.pp, manifests/params.pp, spec/classes/uchiwa_spec.rb, templates/etc/sensu/uchiwa.json.erb
added in 0.20.0.
See https://docs.uchiwa.io/getting-started/configuration/#users-options
Closes #77
=> Support the new UsersOptions hash

manifests/init.pp
Default sensu_api_endpoints variable should be `host` not `hostname`. This just corrects the Parameters listing in init.pp
=> Correct default entry for sensu_api_endpoints

.travis.yml, Gemfile, Gemfile.lock, manifests/init.pp, manifests/repo/yum.pp, spec/classes/uchiwa_spec.rb
Old URI is not valid anymore. Updating to `repositories.sensuapp.org`. Rspec test also updated with new URI.
=> Update repo URI for YUM

manifests/init.pp, manifests/params.pp, manifests/repo/apt.pp, spec/classes/uchiwa_spec.rb
* Use https protocol for mirror stuff
* Get rid of 'sensu' suit in mirror path, since it contains old
packages
=> Switch packages mirror protocol to https

manifests/params.pp, metadata.json
Issue link: https://github.com/Yelp/puppet-uchiwa/issues/85
I took a look at the module to make sure there wasn't anything that wouldn't function with the latest version of puppetlabs-apt (5.0.1), and it seems pretty straightforward, nothing that shouldn't work.
I have the module running cleanly on Ubuntu 14.04.5 and 16.04.4 so I added those to the supported OS list as well. I see no reason why this wouldn't run on Debian 8 at the least, and probably 9 as well, but I didn't have any VMs handy to try installing on.
I noticed a bit of redundant logic in the params class and cleaned that up also.
=> Module Requirements Update, Issue #85
